### ISSUE TITLE
apache module requires ansible_lib but the dependency is not listed

### ISSUE THREAD

**Issue by seraphire** [vbotka/ansible-apache#1]
I installed the apache module using:

`$ ansible-galaxy install vbotka.apache`

and with no other modules installed on my ansible server, when I attempted to run this module, I received the error: 

     TASK [vars: Include OS vars] 
     ERROR! the role 'vbotka.ansible_lib' was not found in {list of library directories}
     The error appears to be in '/usr/home/deployment/.ansible/roles/vbotka.apache/tasks/vars.yml': line 10, column 15, but may
     be elsewhere in the file depending on the exact syntax problem.
  
     The offending line appears to be:

      include_role:
        name: vbotka.ansible_lib
              ^ here

Installing this module appears to correct this problem.  I suspect (though I have yet to test) that adding vbotka.ansible_lib as a dependency should fix this issue.

**Comment by vbotka** [comment]
Both issues were fixed in 1.9.0. Let me know if it's working for you. Details are described in [annotated source code](https://ansible-apache.readthedocs.io/en/1.9.0/configure.html#configure-confd).

**Comment by vbotka** [comment]
Closed. But, feel free to reopen if needed.

**Comment by vbotka** [comment]
Closed.
